name: Download Builder
on:
  workflow_dispatch:

jobs:
  make_rootfs:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Set Timezone
        run: |
          echo "Setting timezone to Asia/Jakarta"
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Depedency
        run: |
          sudo -E apt-get update > /dev/null 2>&1
          sudo -E apt install net-tools make gawk git curl unzip bzip2 > /dev/null 2>&1
          sudo -E apt install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt) > /dev/null 2>&1
        
      - name: Download Builder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv8/openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz > /dev/null 2>&1
          mkdir -p tmp > /dev/null 2>&1
          mkdir -p tmp/files > /dev/null 2>&1
          tar -xf openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz -C tmp --strip-components=1 > /dev/null 2>&1
          rm -rf openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz > /dev/null 2>&1

      - name: Copy files and Ipk
        run: |
          echo -e "Copy Files"; cp -rf files/files/* tmp/files/;
          echo -e "Copy IPK"; cp -rf files/ipk/* tmp/packages/;
          echo -e "Copy Feeds"; cp -rf files/repositories.conf tmp/;

      - name: Make Rootfs
        run: |
          cd tmp > /dev/null 2>&1
          make image PROFILE="generic" PACKAGES=" \
          -dnsmasq \
          cgi-io libiwinfo libiwinfo-data libiwinfo-lua liblua liblucihttp liblucihttp-lua \
          libubus-lua lua luci luci-app-firewall luci-app-opkg luci-base luci-lib-base \
          luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network \
          luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-ssl \
          luci-theme-material rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci \
          rpcd-mod-rrdns uhttpd uhttpd-mod-ubus luci-compat \
          ath9k-htc-firmware btrfs-progs hostapd hostapd-utils kmod-ath kmod-ath9k kmod-ath9k-common \
          kmod-ath9k-htc kmod-cfg80211 kmod-crypto-acompress kmod-crypto-crc32c kmod-crypto-hash \
          kmod-fs-btrfs kmod-mac80211 wireless-tools wpa-cli wpa-supplicant libc php8 \
          zoneinfo-core zoneinfo-asia nano htop unzip wget wget-ssl libmbedtls tar bash \
          netdata httping coreutils-timeout kmod-usb-net-rndis \
          usbutils kmod-usb-net-cdc-ether usb-modeswitch openssh-sftp-server \
          kmod-usb-net-huawei-cdc-ncm kmod-usb-serial-wwan luci-app-3ginfo-lite \
          perlbase-file kmod-brcmutil perlbase-essential perlbase-utf8 \
          perlbase-file  perlbase-time perlbase-xsloader coreutils-stat \
          luci-app-amlogic luci-app-ttyd luci-app-diskman luci-app-openclash luci-app-tinyfm \
          " FILES="files" || true

      - name: Move Rootfs
        run:
          echo -e "Move Rootfs"; mv tmp/bin/targets/armsr/armv8/openwrt-23.05.5-armsr-armv8-generic-rootfs.tar.gz /home/runner/work/Mutiara-Wrt/Mutiara-Wrt/;
          echo -e "Remove tmp"; rm -rf tmp;

      - name: Upload Rootfs
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-rootfs
          path: openwrt-23.05.5-armsr-armv8-generic-rootfs.tar.gz
          
  build_firmware:
    runs-on: ubuntu-22.04
    needs: make_rootfs
    steps:
      - name: Download Rootfs
        uses: actions/download-artifact@v3
        with:
          name: openwrt-rootfs

      - name: Clone Amlogic Builder
        run: |
          git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
          cd amlogic-s9xxx-openwrt
          mkdir -p openwrt-armvirt

      - name: Move Rootfs
        run: |
          mv openwrt-23.05.5-armsr-armv8-generic-rootfs.tar.gz amlogic-s9xxx-openwrt/openwrt-armvirt/

      - name: Build Firmware HG680P
        run: |
          cd amlogic-s9xxx-openwrt
          sudo ./remake -b s905x -k 5.15 -s 1024

      - name: Build Firmware B860H
        run: |
          cd amlogic-s9xxx-openwrt
          sudo ./remake -b s905x-b860h -k 5.15 -s 1024

      - name: Find Firmware
        run: |
          IMG_PATH=$(find -name "openwrt*.img.gz")
          echo "IMG_PATH=$IMG_PATH" >> $GITHUB_ENV
          echo -e "Image path: $IMG_PATH"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          name: Amlogic Firmware Release
          tag_name: v1.0.0
          draft: false
          prerelease: false
          files: |
                ${{ env.IMG_PATH }}
          body: |
            ### OpenWrt Image information
            - Default IP: 192.168.1.1
            - Default username: root
            - Default password: mutiara
            - Default WIFI name: Mutiara-Wrt
